### ISSUE TITLE
Reading files does not produce expected output with nontrivial file sizes

### ISSUE THREAD

**Issue by michaxm** [jystic/hadoop-rpc#8]
I played with it around in https://github.com/michaxm/hdaoop-rpc-exploration, but experienced incomplete, garbled output when reading files from HDFS with for examle this code:

    import qualified Data.ByteString.Char8 as BC
    import qualified Data.Text as T
    ...

    main :: IO ()
    main = do
      args <- getArgs
      case args of
       ("print": user: path: nodes) -> printHdfsFile (mkConfig user nodes) path
       ("copyToLocal": destFile: user: path: nodes) -> copyHdfsFileToLocal destFile (mkConfig user nodes) path
       _ -> error "usage: command [cmd-args] user path nodes\n commands:\n print\n copyToLocal destFile"
      where
        mkConfig u ns = HadoopConfig (T.pack u) (map toEndpoint ns) Nothing
          where
            toEndpoint :: String -> Endpoint
            toEndpoint str = let es = splitOn ":" str in if length es == 2 then Endpoint (T.pack $ es !! 0) (read $ es !! 1) else error $ "illegal host: "++str

    printHdfsFile :: HadoopConfig -> String -> IO ()
    printHdfsFile = withHdfsReader print

    copyHdfsFileToLocal :: FilePath -> HadoopConfig -> String -> IO ()
    copyHdfsFileToLocal destFile = withHdfsReader $ BC.writeFile destFile

    withHdfsReader :: (BC.ByteString -> IO ()) -> HadoopConfig -> String -> IO ()
    withHdfsReader action config path =  do
      readHandle_ <- runHdfs' config $ openRead $ BC.pack path
      case readHandle_ of
       (Just readHandle) -> hdfsMapM_ action readHandle
       Nothing -> error "no read handle"

This worked for trivial files, but when reading files with at least some KB in size, copied data was less than expected, for example a 44 MB file in HDFS produced a file 26 KB large. A plain text file (CSV, only numbers and spaces) with 74 KB produced only 10 KB and the first lines were not the first lines of the original.

I tried the automatic configuration detection as well (the code above does not reflect that), as this seems to be some sort of chunking issue, the chunks are however too small to expect HDFS file chunking issues. Did I fuck up the character conversion?

**Comment by jystic** [comment]
I think the problem is that `hdfsMapM_` will stream you a chunk of the file at a time over the network. So it looks like you're overwriting the file with each chunk and therefore only getting the last one.I think something like this should work:

```haskell
import System.IO (IOMode(..), withBinaryFile)
-- snip --
copyHdfsFileToLocal :: FilePath -> HadoopConfig -> String -> IO ()
copyHdfsFileToLocal destFile =
  withBinaryFile destFile WriteMode $ \h -> withHdfsReader $ BC.hPut h
```

**Comment by michaxm** [comment]
Thanks for pointing that out, stupid mistake. Reading files (60-70MB) is 1-2 orders of magnitude faster than with hdfs dfs (sometimes 1, sometimes 2, probably related to block file locations).

I took the liberty of putting that example in the documentation, but feel free to discard that: https://github.com/jystic/hadoop-rpc/pull/10
